//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFT.Market.SourceGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFT.Market.SourceGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetType,Name
        ///Crypto,Bitcoin
        ///Crypto,Etherium.
        /// </summary>
        internal static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortName ///CME ///GLOBEX ///NYSE ///NASDAQ ///SGX ///CBOE ///LIFFE ///NYMEX ///ICE ///EUREX ///LSE ///ACE ///AMEX ///ARCA ///BELFOX ///BSE ///BOX ///BRUT ///BTRADE ///CFE ///DEFAULT ///ECBOT ///EUREXSW ///EUREXUS ///FTA ///HKFE ///IBIDEAL ///IBTMBR ///IBVWAP ///IDEM ///INCA ///ISE ///ISLAND ///ME ///MEFF ///MONEP ///NNM ///NQLX ///NSCM ///OES ///ONE ///OPRA ///OSE ///OTCBB ///PHLX ///PSE ///REDI ///SDOT ///SFE ///SFX ///SNFE ///SOES ///SWB ///SWX ///TSE ///TSX ///TSXV ///VIRTX ///XETRA ///IBIDEALPRO ///NYBOT ///CAES ///IPE ///MATIF ///BROKERTEC ///CLEARPORT ///KSE ///LIFFECOMMODITIES ///AEB ///ASX ///AEX ///NSE ///BVME ///HKEX ///SBF ///BM ///VSE ///SFB ///OMX ///MEXI ///BOVESPA ///TERABIT ///NADEX /// ///# Crypto exchanges ///Binance ///BinanceFutures ///BitMex ///F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Exchanges {
            get {
                return ResourceManager.GetString("Exchanges", resourceCulture);
            }
        }
    }
}
